### ISSUE TITLE
Stuck on start scanning...

### ISSUE THREAD

**Issue by sebastian-ruiz** [marcelkottmann/mkh-controller#1]
Hi! Your project looks great!

I am trying to use it with my Mould King 4.0 powered module, that I bought here: https://www.amazon.de/-/en/gp/product/B09KY8LL3Y/

But it doesn't work. It is stuck on `start scanning...`

Maybe the `MOULD_KING_HUB_SCAN_SERVICE_UUID` is different for me? How do I find out what it is? Thanks.

I can connect to the Mould King via the iPhone app.

**Comment by marcelkottmann** [comment]
Hi @sebastian-ruiz , from the link you posted I see that the module you are using is a MK controller not a MKH controller. The MKH Controller modules are in a white housing ( see https://www.amazon.de/Mould-King-13181-APP-Programmierung-Display-Spielzeug/dp/B0CHN4LPC9)
The blutooth IDs will be different and the data sent through bluetooth will most likely look completely different.
From what I know the difference between MKH and MK controler is that the MKH controller can control the step motors where the MK controller can only start/stop motors with different speeds.
I reverse engineered the bluetooth Ids with the Android App "nRF connect".
